#! /bin/sh
_() { bspc config "$@";  }
R() { bspc rule -a "$@"; }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

#########
# SXHKD #
#########
. $XDG_CONFIG_HOME/sxhkd/normal.mode

####################
# General settings #
####################
bspc monitor -d I II III IV V VI VII VIII IX X 

gaps=$(xrdbvar bspwm.gaps)
outergaps=$(xrdbvar bspwm.outergaps)
#padding=$(( $outergaps - $gaps ))

_ border_width          $(xrdbvar bspwm.borderpx)
_ window_gap            $gaps
  bspc-padding          reset

_ focus_follows_pointer true
_ ignore_ewmh_focus     true

_ split_ratio           0.55
_ borderless_monocle    false
_ gapless_monocle       false

_ normal_border_color   "$(xrdbvar bspwm.innerbordernormal)"
_ active_border_color   "$(xrdbvar bspwm.innerbordernormal)"
_ focused_border_color  "$(xrdbvar bspwm.innerbordernormal)"
_ presel_feedback_color "$(xrdbvar bspwm.presel_color)"

###################
# Window settings #
###################

#R Gimp              desktop='^4' follow=on
#R Spotify           desktop='^9' pseudo_tiled=on
#R Darktable         desktop='^3' follow=on
#R discord           desktop='^4' follow=on
#R jetbrains-idea-ce desktop='^2' follow=on
#R libreoffice       desktop='^3' follow=on

R '*:floating'      state=floating
R 'floating:*'      state=floating
R '*:scratch1'      state=floating #sticky=on
R '*:scratch2'      state=floating #sticky=on
R '*:scratch3'      state=floating #sticky=on
R Zathura           state=tiled

#############
# Autostart #
#############
# Start bar
startbarbspwm &

# Start window swallowing script
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'
pgrep -fl 'pidswallow -gl' || pidswallow -gl &

