#!/bin/sh
_() { bspc config "$@";  }
R() { bspc rule -a "$@"; }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

#########
# SXHKD #
#########
pgrep -x sxhkd > /dev/null || sxhkd &

###########
# GENERAL #
###########
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

gaps=$(xrdbvar bspwm.gaps)
padding=$(( $(xrdbvar bspwm.outergaps) - $gaps ))
bargaps=$(( $(xrdbvar bar.height) + $(xrdbvar bar.y) + 2 * $(xrdbvar bar.border) - ($gaps / 2) ))
bottombar=$(xrdbvar bar.bottom)

_ border_width   $(xrdbvar bspwm.borderpx)
_ window_gap     $gaps
_ left_padding   $padding
_ right_padding  $padding

if [ "$bottombar" = "true" ]; then 
    _ top_padding    $padding
    _ bottom_padding $bargaps
else 
    _ top_padding    $bargaps
    _ bottom_padding $padding
fi

_ ignore_ewmh_focus     true
_ focus_follows_pointer true
_ pointer_modifier      mod1
_ pointer_action1       move
_ pointer_action2       resize_side

_ split_ratio           0.55
_ single_monocle        true
_ borderless_monocle    true
_ gapless_monocle       false
_ automatic_scheme      alternate

_ normal_border_color   "$(xrdbvar bspwm.innerbordernormal)"
_ active_border_color   "$(xrdbvar bspwm.innerbordernormal)"
_ focused_border_color  "$(xrdbvar bspwm.innerborderfocused)"
_ presel_feedback_color "$(xrdbvar bspwm.presel_color)"

_ external_rules_command $XDG_CONFIG_HOME/bspwm/external_rules.sh

###################
# Window settings #
###################
R '*:eterm8'        state=floating
R '*:floating'      state=floating
R 'floating:*'      state=floating
R '*:scratch1'      state=floating sticky=on
R '*:scratch2'      state=floating sticky=on
R '*:scratch3'      state=floating sticky=on
R Zathura           state=tiled

#############
# Autostart #
#############

bspc-auto-unhide &
startbarbspwm &
