#!/bin/bash
FILE="$XDG_CONFIG_HOME/bsp-layout/layoutrc" 

line=$(grep "TALL_RATIO" $FILE)
value=${line#*=}
value=${value%;*}

min=0.1
max=0.9

value=$(echo "$value $1" | bc)

if (( $(echo "$value < $min" | bc -l) )); then
    value=$min
elif (( $(echo "$value > $max" | bc -l) )); then
    value=$max
fi

echo "TALL_RATIO=$value;" > $FILE
echo "WIDE_RATIO=$value;" >> $FILE
