#!/bin/bash

# Get current layout (to be displayed in prompt)
current=$(bsp-layout get $(bspc query -D -d --names))
# (no layout equals default tiled layout)
[[ $current = "-" ]] && current="tiled"

case "$1" in
    # if --remove is passed, set layout to default (tiled)
    --remove)
        bsp-layout set tiled
        exit 0
    ;;
    # if --remove-all is passed, set all desktop layouts to default
    --remove-all)
        for desktop in $(bspc query -D --names); do
            bsp-layout set tiled $desktop
        done
        exit 0
    ;;
    *) ;;
esac

# Get available layouts
options=$(bsp-layout layouts)

# Get user choice (and display current layout in prompt)
choice=$(echo "${options[@]}" | dmenu -i -F -p "Layout_($current)")

# If no choice, exit
[[ -z $choice ]] && exit 0

# If choice is not a valid layout, exit
[[ "( ${options[@]} )" =~ "$choice" ]] || exit 0

# If --once is passed, apply only once
if [ "$1" = "--once" ]; 
then
    bsp-layout once $choice 
else
    # Else, set layout
    bsp-layout set $choice 
fi
