#!/bin/bash

flags=( marked locked sticky private )

# String for all the current flags of the node
set_flags=""

# Iterate over the available flags
for flag in "${flags[@]}"
do
    # Check if flag is set
    if ( bspc query -N -n focused.$flag > /dev/null ); then
        # If flag strign is empty, set it to the current flag
        if [ -z $set_flags ]; then
            set_flags="$flag"
        # If not empty, append the current flag to the existing ones
        else
            set_flags="$set_flags|$flag"
        fi
    fi
done

# Create prompt
prompt="Toggle flags"

[[ -z $set_flags ]] || prompt="$prompt ($set_flags)"

# Get user choice
choice=$(printf "%s\n" "${flags[@]}" | dmenu -i -F -p "$prompt")

# Exit if no choice
[[ -z $choice ]] && exit 0

# Set flag
bspc node -g $choice
