#/bin/sh
userresources=$XDG_CONFIG_HOME/X/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Font
xset +fp /home/xan/.local/share/fonts/
xset fp rehash

# Increase key repeat rate
xset r rate 300 50 &

# Turn off system beep
xset b off &
xset b 0 0 0 &

# Swap caps and escape 
setxkbmap -option caps:swapescape &

# Make sure cursor is not an X when hovering over root window
xsetroot -cursor_name left_ptr &

# Startup
nvidia-settings -l --config=$XDG_CONFIG_HOME/nvidia-settings/nvidia-settings-rc &
picom &
unclutter --timeout 1 &
redshift -l 57.7089:11.9746 &
#flashfocus &
setwp &
dropbox-wrapper start &

spotify &
$BROWSER &

# Send notifications regarding battery usage
battery-notify &

# Remind me about things I want to be reminded of
remember remind 3600s &

# Start window manager
exec bspwm
